const SELECT_COURSE = 'SELECT_COURSE';
const UNSELECT_COURSE = 'UNSELECT_COURSE';
const LOGIN_SUCCESS= 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';

module.exports = {
  SELECT_COURSE,
  UNSELECT_COURSE,
  LOGIN_SUCCESS,
  LOGIN_FAILURE
};
