export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const DISPLAY_NOTIFICATION_DRAWER = "LOGDISPLAY_NOTIFICATION_DRAWERIN"
export const HIDE_NOTIFICATION_DRAWER = "HIDE_NOTIFICATION_DRAWER"
